baseURL = "https://jorgeluisyh.github.io/blog/"
languageCode = "en-us"
theme = "aafu"
publishDir = "docs"

[params]
    title = "Jorge Yupanqui"
    author = "Jorge Yupanqui"
    description = "Website title"
    copyright = "©"
    useDarkTheme = true

   [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Jorge L. Yupanqui H."
        tagline = "Geographic Engineer"
        location = "Lima, Perú"
        photo = "profile.jpg"

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            class = "fab"
            icon = "fa-linkedin-in"
            url = "https://www.linkedin.com/in/jorge-luis-yupanqui-herrera-72ba5254/"
            title = "LinkedIn"		
        #[[params.social.list]]
        #    class = "fab"
        #    icon = "fa-stack-overflow"
        #    url = "#"
        #    title = "StackOverflow"
        [[params.social.list]]
            class = "fab"
            icon = "fa-github"
            url = "https://github.com/jorgeluisyh"
            title = "GitHub"
        [[params.social.list]]
            class = "fab"
            icon = "fa-twitter"
            url = "#"
            title = "Twitter"
        #[[params.social.list]]
        #    class = "ai"
        #    icon = "ai-google-scholar"
        #    url = "#"
        #    title = "Google Scholar"
        [[params.social.list]]
            class = "fab"
            icon = "fa-facebook-square"
            url = "https://www.facebook.com/JorgeLuisYH"
            title = "facebook"

        [[params.social.list]]
            class = "far"
            icon = "fa-envelope"
            url = "mailto:jorgeluisyh@gmail.com"
            title = "gmail"

        [[params.social.list]]
            class = "fab"
            icon = "fa-whatsapp"
            url = "https://api.whatsapp.com/send?phone=51930266310&text=Hola%20quiero%20preguntarte"
            title = "whatsapp"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true   # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    #[[params.showInAccordion]]
    #    item = "publication"
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby"

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = "**Geographic Engineer**, with experience as a Geographic Information System (GIS) analyst, using related programming languages as Python, proactive attitude, in constantly search of learning and personal improvement, always compromised with current activities and tasks, with ability to work in teams."

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Job Title"
            dates = "2019 - *Present*"
            company = "Company Name"
            details = "Printed from desktop. Sent [emails](#). Called people using telephone. Drank water from office cooler. Ate donuts on people's birthdays."
        [[params.experience.list]]
            position = "Job Title"
            dates = "2018 - 2019"
            link = "#"
            company = "Company Name"

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Ph.D. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_link = "#"
        [[params.education.list]]
            degree = "M.S. in Subject"
            college = "University of State-City"
            dates = "2013 - 2018"
            thesis_title = "Effect of humans on other humans: a study of human behavior."
            thesis_link = "#"
        [[params.education.list]]
            degree = "B.S. in Subject"
            college = "University of State-City"
            dates = "2004 - 2009"

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"

        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"
        [[params.publication.list]]
            title = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."
            authors = "F Last, F Second, P secondary"
            date = "2018"
            journal = "Journal of Field 52 (16), 9033-9044"
            link = "#"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"
        [[params.project.list]]
            title = "project"
            url = "#"
            description = "Description of the project"            

    # Skill section
    [params.skill]
        title = "Skills"
        icon = "fas fa-cogs"

        [[params.skill.list]]
            skill = "English"
            skillrating = 90
        [[params.skill.list]]
            skill = "Geographic Information System"
            skillrating = 80
        [[params.skill.list]]
            skill = "Programming"
            skillrating = 60

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"

        [[params.hobby.list]]		
            hobby = "Playing football"
        [[params.hobby.list]]		
            hobby = "Watching series"
        [[params.hobby.list]]		
            hobby = "Treaking"
        [[params.hobby.list]]     
            hobby = "Traveling"